DISTRICTS = [
    {
        "id": "pudong",
        "name": "浦东新区",
        "short": "浦东",
        "yield": 2.82,
        "budget": 1180,
        "rent": 16250,
        "saleSample": 82,
        "rentSample": 67,
        "score": 91,
        "trend": "+0.21%",
        "labelX": 555,
        "labelY": 224,
        "polygon": "430,85 620,60 710,120 705,235 642,298 640,412 532,470 470,380 470,290 420,220",
        "communities": [
            {
                "id": "zhangjiang-park",
                "name": "张江汤臣豪园",
                "districtId": "pudong",
                "x": 548,
                "y": 188,
                "avgPriceWan": 980,
                "monthlyRent": 16500,
                "yield": 2.86,
                "score": 94,
                "sample": 28,
                "buildingCount": 7,
                "buildingFocus": "5号楼",
                "note": "地铁与产业园双重支撑，租金黏性强，楼层价差相对温和。",
                "buildings": [
                    {"name": "2号楼", "totalFloors": 18, "low": 2.61, "mid": 2.74, "high": 2.58, "score": 80},
                    {"name": "5号楼", "totalFloors": 24, "low": 2.78, "mid": 2.92, "high": 3.08, "score": 94},
                    {"name": "7号楼", "totalFloors": 22, "low": 2.73, "mid": 2.81, "high": 2.77, "score": 86},
                ],
            },
            {
                "id": "lianyang-city",
                "name": "联洋年华",
                "districtId": "pudong",
                "x": 598,
                "y": 232,
                "avgPriceWan": 1260,
                "monthlyRent": 17800,
                "yield": 2.41,
                "score": 73,
                "sample": 24,
                "buildingCount": 5,
                "buildingFocus": "3栋",
                "note": "总价抬升明显，适合作为高净值长持标的，不是当前套利主战场。",
                "buildings": [
                    {"name": "1栋", "totalFloors": 16, "low": 2.22, "mid": 2.35, "high": 2.27, "score": 66},
                    {"name": "3栋", "totalFloors": 18, "low": 2.34, "mid": 2.44, "high": 2.49, "score": 73},
                    {"name": "5栋", "totalFloors": 18, "low": 2.29, "mid": 2.41, "high": 2.36, "score": 70},
                ],
            },
            {
                "id": "biyun-mansion",
                "name": "碧云天第",
                "districtId": "pudong",
                "x": 522,
                "y": 275,
                "avgPriceWan": 890,
                "monthlyRent": 14900,
                "yield": 2.67,
                "score": 88,
                "sample": 21,
                "buildingCount": 4,
                "buildingFocus": "B座",
                "note": "外籍租客占比较高，空置波动要单独折现。",
                "buildings": [
                    {"name": "A座", "totalFloors": 14, "low": 2.46, "mid": 2.61, "high": 2.57, "score": 79},
                    {"name": "B座", "totalFloors": 20, "low": 2.58, "mid": 2.76, "high": 2.83, "score": 88},
                    {"name": "C座", "totalFloors": 16, "low": 2.44, "mid": 2.51, "high": 2.47, "score": 74},
                ],
            },
        ],
    },
    {
        "id": "minhang",
        "name": "闵行区",
        "short": "闵行",
        "yield": 2.66,
        "budget": 760,
        "rent": 10450,
        "saleSample": 69,
        "rentSample": 55,
        "score": 87,
        "trend": "+0.17%",
        "labelX": 320,
        "labelY": 360,
        "polygon": "120,278 240,248 360,255 448,325 418,442 310,482 205,468 118,398",
        "communities": [
            {
                "id": "qibao-yunting",
                "name": "七宝云庭",
                "districtId": "minhang",
                "x": 266,
                "y": 335,
                "avgPriceWan": 650,
                "monthlyRent": 11800,
                "yield": 2.91,
                "score": 92,
                "sample": 30,
                "buildingCount": 6,
                "buildingFocus": "9幢",
                "note": "低总价高出租活跃度，适合本地样本演示。",
                "buildings": [
                    {"name": "3幢", "totalFloors": 12, "low": 2.63, "mid": 2.75, "high": 2.71, "score": 83},
                    {"name": "9幢", "totalFloors": 18, "low": 2.84, "mid": 2.96, "high": 3.04, "score": 92},
                    {"name": "11幢", "totalFloors": 18, "low": 2.67, "mid": 2.79, "high": 2.83, "score": 86},
                ],
            },
            {
                "id": "xinzhuang-hub",
                "name": "莘庄都会里",
                "districtId": "minhang",
                "x": 340,
                "y": 385,
                "avgPriceWan": 580,
                "monthlyRent": 9800,
                "yield": 2.69,
                "score": 85,
                "sample": 26,
                "buildingCount": 5,
                "buildingFocus": "2号楼",
                "note": "交通枢纽优势明显，但房龄带来部分维护折价。",
                "buildings": [
                    {"name": "2号楼", "totalFloors": 14, "low": 2.62, "mid": 2.75, "high": 2.81, "score": 85},
                    {"name": "4号楼", "totalFloors": 12, "low": 2.51, "mid": 2.59, "high": 2.56, "score": 78},
                    {"name": "8号楼", "totalFloors": 16, "low": 2.44, "mid": 2.63, "high": 2.66, "score": 81},
                ],
            },
        ],
    },
    {
        "id": "yangpu",
        "name": "杨浦区",
        "short": "杨浦",
        "yield": 2.54,
        "budget": 920,
        "rent": 13300,
        "saleSample": 51,
        "rentSample": 42,
        "score": 79,
        "trend": "+0.09%",
        "labelX": 392,
        "labelY": 144,
        "polygon": "348,84 452,90 514,140 478,230 386,214 350,154",
        "communities": [
            {
                "id": "wujiaochang-one",
                "name": "五角场壹里",
                "districtId": "yangpu",
                "x": 410,
                "y": 156,
                "avgPriceWan": 880,
                "monthlyRent": 13600,
                "yield": 2.46,
                "score": 76,
                "sample": 22,
                "buildingCount": 4,
                "buildingFocus": "6幢",
                "note": "学区与商圈双属性，挂牌会有情绪溢价。",
                "buildings": [
                    {"name": "2幢", "totalFloors": 18, "low": 2.29, "mid": 2.41, "high": 2.35, "score": 71},
                    {"name": "6幢", "totalFloors": 24, "low": 2.38, "mid": 2.54, "high": 2.62, "score": 76},
                ],
            }
        ],
    },
    {
        "id": "putuo",
        "name": "普陀区",
        "short": "普陀",
        "yield": 2.38,
        "budget": 790,
        "rent": 10800,
        "saleSample": 49,
        "rentSample": 43,
        "score": 74,
        "trend": "+0.05%",
        "labelX": 176,
        "labelY": 156,
        "polygon": "92,116 218,88 246,148 216,238 118,252 84,182",
        "communities": [
            {
                "id": "zhenru-harbor",
                "name": "真如港湾",
                "districtId": "putuo",
                "x": 164,
                "y": 176,
                "avgPriceWan": 710,
                "monthlyRent": 11100,
                "yield": 2.53,
                "score": 77,
                "sample": 19,
                "buildingCount": 3,
                "buildingFocus": "7号楼",
                "note": "适合做中等预算样本池，租金相对稳定。",
                "buildings": [
                    {"name": "1号楼", "totalFloors": 14, "low": 2.39, "mid": 2.47, "high": 2.44, "score": 70},
                    {"name": "7号楼", "totalFloors": 18, "low": 2.45, "mid": 2.58, "high": 2.63, "score": 77},
                ],
            }
        ],
    },
    {
        "id": "baoshan",
        "name": "宝山区",
        "short": "宝山",
        "yield": 2.72,
        "budget": 530,
        "rent": 7900,
        "saleSample": 47,
        "rentSample": 37,
        "score": 83,
        "trend": "+0.14%",
        "labelX": 526,
        "labelY": 100,
        "polygon": "456,20 612,16 676,78 620,126 522,138 452,94",
        "communities": [
            {
                "id": "gongkang-hill",
                "name": "共康新城",
                "districtId": "baoshan",
                "x": 542,
                "y": 90,
                "avgPriceWan": 460,
                "monthlyRent": 8600,
                "yield": 2.98,
                "score": 90,
                "sample": 25,
                "buildingCount": 5,
                "buildingFocus": "12幢",
                "note": "低总价 + 交通改善预期，适合打榜。",
                "buildings": [
                    {"name": "6幢", "totalFloors": 11, "low": 2.77, "mid": 2.85, "high": 2.81, "score": 82},
                    {"name": "12幢", "totalFloors": 18, "low": 2.86, "mid": 3.01, "high": 3.12, "score": 90},
                ],
            }
        ],
    },
]

PIPELINE_STEPS = [
    {
        "title": "采集层",
        "description": "本地 CSV 与公开页人工采样样本，保留原始文本、原始坐标、抓取时间与页面快照。",
        "meta": "raw_listings_sale / raw_listings_rent",
    },
    {
        "title": "标准化层",
        "description": "做小区别名归一、楼栋文本抽取、楼层解析与价格单位统一，生成标准实体。",
        "meta": "community_aliases / listing_normalized",
    },
    {
        "title": "去重层",
        "description": "按面积、楼层、朝向、价格接近度进行跨平台聚类，产出去重组与置信度。",
        "meta": "listing_dedup_groups",
    },
    {
        "title": "空间层",
        "description": "内部保留 GCJ-02 与 WGS-84 双字段，前端与 Google Earth 各取所需。",
        "meta": "communities / buildings / geom",
    },
    {
        "title": "指标层",
        "description": "按小区、楼栋、楼层桶计算租售比、年化回报率、样本量与机会评分。",
        "meta": "metrics_community / metrics_building_floor",
    },
]

SCHEMAS = [
    {
        "name": "communities",
        "description": "小区维表，存小区名、别名、板块、中心点和 polygon。",
        "fields": "community_id, district_id, aliases_json, centroid, polygon_geojson",
    },
    {
        "name": "buildings",
        "description": "楼栋实体，关联小区、楼栋号、总层数和空间几何。",
        "fields": "building_id, community_id, building_no, total_floors, geom",
    },
    {
        "name": "listings_sale",
        "description": "在售房源事实表，保留源字段与标准化字段并行。",
        "fields": "source_listing_id, raw_address, floor_no, area_sqm, price_total_wan",
    },
    {
        "name": "listings_rent",
        "description": "出租房源事实表，用于年租金回报率和空置波动分析。",
        "fields": "source_listing_id, monthly_rent, floor_no, orientation, published_at",
    },
    {
        "name": "metrics_building_floor",
        "description": "楼栋 + 楼层桶指标快照，用于地图弹窗和机会榜排序。",
        "fields": "building_id, floor_bucket, yield_pct, rent_sale_ratio, sample_size, score",
    },
]

SYSTEM_STRATEGY = {
    "map_stack": {
        "primary": {
            "name": "高德地图",
            "role": "中国场景主前端底图与交互容器",
            "why": "适合区级浏览、小区下钻、GeoJSON 覆盖物、弹窗和筛选交互。",
        },
        "secondary": {
            "name": "Google Earth / KML",
            "role": "内部分析、导出、演示与人工巡检",
            "why": "适合飞行浏览、结果分享和研究员内部可视化，不建议作为中国业务主地图。",
        },
    },
    "coordinate_policy": {
        "storage": "原始坐标 + 统一标准坐标双写",
        "china_web": "GCJ-02 优先",
        "google_earth": "WGS-84 导出",
    },
    "data_policy": {
        "priority": "公开开放数据 / 自有 CSV / 手工校正优先",
        "fallback": "半自动导入或低频人工校正",
        "risk_note": "避免把长期工具建立在不稳定抓取链路上。",
    },
    "address_model": [
        "district",
        "resblock",
        "building",
        "unit",
        "floor",
    ],
}

DATA_SOURCES = [
    {
        "id": "shanghai-open-data-community",
        "name": "上海开放数据 · 物业小区信息",
        "category": "open_data",
        "priority": "medium",
        "coverage": "小区名称 / 地址 / 字典归一",
        "role": "社区字典、别名标准化与去重底座",
    },
    {
        "id": "authorized-batch-import",
        "name": "授权批次导入",
        "category": "manual_import",
        "priority": "medium",
        "coverage": "出售 / 出租 CSV、地址归一、楼层证据批次",
        "role": "官方接口尚未完全打通前的合法过渡链路",
    },
    {
        "id": "amap-aoi-poi",
        "name": "高德 AOI / POI / District",
        "category": "map_enrichment",
        "priority": "medium",
        "coverage": "行政区、板块、小区 AOI、地理增强",
        "role": "地图展示与空间补全",
    },
]

ADDRESS_QUEUE = [
    {
        "queueId": "addr-001",
        "communityId": "zhangjiang-park",
        "buildingNo": "5号楼",
        "floorNo": 17,
        "sourceId": "authorized-batch-import",
        "rawAddress": "浦东新区张江路xx弄5号楼17层1702",
        "normalizedPath": "浦东新区 / 张江汤臣豪园 / 5号楼 / 2单元 / 17层 / 1702",
        "status": "resolved",
        "confidence": 0.96,
        "lastActionAt": "2026-04-11 09:18",
        "reviewHint": "已匹配楼栋号与楼层，自动进入指标层。",
    },
    {
        "queueId": "addr-002",
        "communityId": "zhangjiang-park",
        "buildingNo": "5号楼",
        "floorNo": 24,
        "sourceId": "public-browser-sampling",
        "rawAddress": "张江汤臣豪园5号楼顶层复式",
        "normalizedPath": "浦东新区 / 张江汤臣豪园 / 5号楼 / 待识别单元 / 24层",
        "status": "needs_review",
        "confidence": 0.79,
        "lastActionAt": "2026-04-11 08:42",
        "reviewHint": "缺少单元号，建议结合 AOI 和人工校正补齐。",
    },
    {
        "queueId": "addr-003",
        "communityId": "qibao-yunting",
        "buildingNo": "9幢",
        "floorNo": 12,
        "sourceId": "authorized-batch-import",
        "rawAddress": "七宝云庭9幢12楼1201",
        "normalizedPath": "闵行区 / 七宝云庭 / 9幢 / 1单元 / 12层 / 1201",
        "status": "resolved",
        "confidence": 0.94,
        "lastActionAt": "2026-04-11 07:55",
        "reviewHint": "命中楼栋别名表，已完成标准化。",
    },
    {
        "queueId": "addr-004",
        "communityId": "gongkang-hill",
        "buildingNo": "12幢",
        "floorNo": 18,
        "sourceId": "public-browser-sampling",
        "rawAddress": "共康新城十二幢18F",
        "normalizedPath": "宝山区 / 共康新城 / 12幢 / 待识别单元 / 18层",
        "status": "matching",
        "confidence": 0.84,
        "lastActionAt": "2026-04-11 10:06",
        "reviewHint": "楼栋已识别，正在等待单元侧补全。",
    },
    {
        "queueId": "addr-005",
        "communityId": "wujiaochang-one",
        "buildingNo": "6幢",
        "floorNo": 19,
        "sourceId": "shanghai-open-data-community",
        "rawAddress": "杨浦区政立路xx弄6幢1903",
        "normalizedPath": "杨浦区 / 五角场壹里 / 6幢 / 3单元 / 19层 / 1903",
        "status": "resolved",
        "confidence": 0.93,
        "lastActionAt": "2026-04-10 21:13",
        "reviewHint": "已与物业小区字典和楼栋 footprint 对齐。",
    },
    {
        "queueId": "addr-006",
        "communityId": "qibao-yunting",
        "buildingNo": "9幢",
        "floorNo": 15,
        "sourceId": "authorized-batch-import",
        "rawAddress": "闵行区七宝云庭9幢高楼层样本",
        "normalizedPath": "闵行区 / 七宝云庭 / 9幢 / 1单元 / 15层",
        "status": "needs_review",
        "confidence": 0.81,
        "lastActionAt": "2026-04-11 20:38",
        "reviewHint": "来自授权 CSV，高楼层被折算为 15 层，建议人工复核。",
    },
]
